### ISSUE TITLE
Update README to include more information

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#1]
Update [README.MD](/Akhliskun/fellcleave/blob/master/README.md) to contain the following structure:

* **Project Name**
* **Description**
  * A description of the project follows. A good description is clear, short, and to the point. Describe the importance of your project, and what it does.
* **Table of Contents**
  *  include a table of contents in order to allow other people to quickly navigate the README.
* **Installation**
  * Tell other users how to install your project locally.
* **Usage**
  * Instruct other people on how to use your project after they’ve installed it. This would also be a good place to include screenshots of your project in action.
* **Contributing**
  * Quick details on how to contribute to the project and a link to our [Conduit](Akhliskun/fellcleave/blob/master/CODE_OF_CONDUCT.md) and [Contributing page](/Akhliskun/fellcleave/blob/master/CONTRIBUTING.md)
* **Credits**
  * Include a section for credits in order to highlight and link to our contributers.
* **License**
  * Include information about our license..

**Comment by danlabici** [comment]
## Task Status:
- [x] ReadMe page updated to contain the new required info.
- [x] Contributing page created.
- [x] Contributing page updated with new helpful resources.
- [x] Code of Conduit page created.
- [x] License page created.
- [x] Pull Request template created.

**Comment by danlabici** [comment]
Work completed.
