### ISSUE TITLE
Content for Lancer

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#11]
## Content wise.
Make sure that every Lancer page has updated content for the:
* Lore
* How To Become
* Best Races
* Jobs that Req. Lancer
* Class Changes in 4.0

## Creatives
* Main Page
  * Replace the concept art with the new .png file.
  * Replace the heading banner.

## Navigation
* Include the navigation links used in the Paladin page.

### Pages which needs attention
* [Lancer](http://fellcleave.com/classes/lancer) - main page
  * [Hunting Logs](http://fellcleave.com/classes/lancer/hunting-logs) - sub page
  * [Leveling Rotation](http://fellcleave.com/classes/lancer/leveling-rotation) - sub page

**Comment by danlabici** [comment]
## Task Status:
**Content**:
- [x] Lore
- [ ] How to become
- [x] Best Races
- [ ] Jobs that req. LNC
- [ ] Changes in 4.0

**Creatives**
- [ ] Replace the concept art
- [ ] Replace the banner

**Navigation**
- [ ] Added the navigation menu.
