### ISSUE TITLE
SEO for DPS Meter Guide

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#20]
## OnPage SEO for the DPS Meter guide page.
Make sure that the dps meter page has the new frontmater and its OnPage SEO is following the strategy.
### Pages which needs attention
* [DPS Meter for FFXIV](http://fellcleave.com/home/advanced-combat-tracker-dps-meter) - main page

**Comment by danlabici** [comment]
## Task Status:
- [ ] New Frontmater added
- [ ] Meta SEO Completed
- [ ] Content SEO Completed
