### ISSUE TITLE
Content for DPS Meter Guide

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#21]
## Content wise.
Make sure that the dps meter guide page has updated content for the:
* What this guide will cover
* Is it Against the rules
* How to install
* Customize
* Setup Recommendations
* FFLogs

## Creatives
* Main Page
  * Replace the screenshots with better editing.
  * Replace the heading banner.

## Navigation
* Include the navigation links at the bottom of the page

### Pages which needs attention
* [DPS Meter for FFXIV](http://fellcleave.com/home/advanced-combat-tracker-dps-meter) - main page

**Comment by danlabici** [comment]
## Task Status:
**Content**:
- [ ] What this guide will cover
- [x] Is it Against the rules
- [x] How to install
- [ ] Customize
- [ ] Setup recommendations
- [ ] FFLogs

**Creatives**
- [x] Replace the banner
- [ ] Replace the concept art

**Navigation**
- [ ] Added the navigation menu.
