### ISSUE TITLE
SEO for Raid Progress

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#22]
## OnPage SEO for the Raid Progress page.
Make sure that the dps meter page has the new frontmater and its OnPage SEO is following the strategy.
### Pages which needs attention
* [Raid Progress](http://fellcleave.com/progress) - main page

**Comment by danlabici** [comment]
## Task Status:
- [ ] New Frontmater added
- [ ] Meta SEO Completed
- [ ] Content SEO Completed
