### ISSUE TITLE
Content for Raid Progress

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#23]
## Content wise.
Update the existing page to include more information on the rankings and include a few more links to top FCs and streamers.

## Creatives
* Main Page
  * Replace the Header mana.gg banner.

## Navigation
* Include the navigation links at the bottom of the page to include a link back to the main page (archive navigation)

## Archive the page
* Archive the current page and give it a link of **/progress/patch4.1-raidname-july-2017**

### Pages which needs attention
* [Raid Progress](http://fellcleave.com/progress) - main page

**Comment by danlabici** [comment]
## Task Status:
**Content**:
- [ ] Added top 10 kills tables for each boss.
- [ ] Included more information on the top FCs and Streamers

**Creatives**
- [ ] Replace the mana.gg banner

**Navigation**
- [ ] Added the navigation menu.

**Archive**
- [ ] Created a new /progress/ page
- [ ] Archived the old page
