### ISSUE TITLE
SEO for Guide Writers

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#24]
## OnPage SEO for the Guide Writers page.
Make sure that the guide writers page has the new frontmater and its OnPage SEO is following the strategy.
### Pages which needs attention
* [FFXIV Guide Writers Needed](http://fellcleave.com/home/guide-writers-needed) - main page

**Comment by danlabici** [comment]
## Task Status:
- [ ] New Frontmater added
- [ ] Meta SEO Completed
- [ ] Content SEO Completed
