### ISSUE TITLE
Content for Guide Writers

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#25]
## Content wise.
Make sure that the guide writers page has updated content for the:
* What we would like
* What we can offer
* What we don't need
* How to apply
* Remove Deadline
* Volunteers

## Navigation
* Include the navigation links at the bottom of the page

### Pages which needs attention
* [FFXIV Guide Writers Needed](http://fellcleave.com/home/guide-writers-needed) - main page

**Comment by danlabici** [comment]
## Task Status:
**Content**:
- [ ] What we would like
- [ ] What we can offer
- [ ] What we don't need
- [ ] How to apply
- [ ] Remove deadline
- [ ] Volunteers

**Navigation**
- [ ] Added the navigation menu.
