### ISSUE TITLE
Content for Astrologian

### ISSUE THREAD

**Issue by danlabici** [Akhliskun/fellcleave#27]
## Content
Make sure that every Astrologian page has updated content for the:
* Lore
* Playstyle
* How to become
* Job gauge
* Role Skills
* Job Changes in 4.0 - 4.1

## Creatives
* Main Page
  * Replace the concept art with the new .png file.
  * Replace the heading banner.

## Navigation
* Include the navigation links.

### Pages which needs attention
* [Astrologian](http://fellcleave.com/jobs/astrologian) - main page
  * [Introduction](http://fellcleave.com/jobs/astrologian/introduction) - sub page
  * [Rotation and Cooldowns](http://fellcleave.com/jobs/astrologian/rotation-and-cooldowns) - sub page
  * [Materia and Consumables](http://fellcleave.com/jobs/astrologian/materia-and-consumables) - sub page
  * [Best in Slot](http://fellcleave.com/jobs/astrologian/best-in-slot) - sub page
  * [Macros](http://fellcleave.com/jobs/astrologian/macros-and-suggestions) - sub page

**Comment by danlabici** [comment]
## Task Status:
- [ ] Main page
  - [x] Lore
  - [ ] Playstyle
  - [ ] How to become
  - [x] Job gauge
  - [x] Role Skills
  - [ ] Changes in 4.0
  - [ ] Changes in 4.1
- [ ] Introduction
  - [ ] General Information
  - [ ] About the author
  - [ ] Job overview
  - [ ] Change has changed 4.1
  - [ ] Strengths
  - [ ] Weaknesses 
  - [ ]  Viability
- [ ] Rotation and Cooldowns
  - [ ] Important Notes
  - [ ] Role Skills
  - [ ] Remove Raid, Dungeon, Solo sections
  - [ ] Single Target
  - [ ] Multi Target
  - [ ] Cooldown usage
  - [ ] Core concepts
- [ ] Materia and Consumables
  - [ ] Optimal Materia
  - [ ] Remove Raids, Dungeons, Solo sections
  - [ ] Optimal Consumables
  - [ ] Remove Raids, Dungeons, Solo sections
- [ ] Best in Slot
  - [ ] From Raids
  - [ ] From Dungeons
  - [ ] Remove Solo content
  - [ ] Loot Competition
- [ ] Macros
  - [ ] Useful macros
  - [ ] Suggestions
